apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laznp-db
  name: laznp-db
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laznp-db
  template:
    metadata:
      labels:
        app: laznp-db
    spec:
      containers:
      - image: mysql
        name: laznp-db
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: laznp-db-data
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-config
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-config
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-config
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-config
                key: MYSQL_DATABASE
      volumes:
      - name: laznp-db-data
        hostPath:
          path: /app/laznp.id/database
          type: DirectoryOrCreate
