apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-tiger-docker
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgC8M+qJw71Gh5z3Ct3Kidz02VQjtbw6oLy145nE0pp/ozwQCsSDp24gNL0RRiSTGvh+zZm7u8VihR2hjdFQFS9Nm+YuLVkxltbPc4D9mG6Q7mfqoLm9hT6tPXerrH4rElUvVmjUtF7LwROTX8O8r/xZByrZuHkyrZZbjybxDdqB0gLZIxXltJXcRXmKY357GXZx6IbRsykxZAgCThUjTDzWyUBN0X3kl5Ny7n2ZtRziI0CjYgXe5roiBmCDsvslUk2vk8TpxB/Ce2jUP6FCD88NWjxNUzHqve7cgZwn3JEN5FjTVvcJ8yZZMK3NtUoZA8EOmMcBhdS+vQFacpvMbBhj0dQzfZff6dVzSTMy/sh05crz3NrhR4ZmbXCZN9/Iw7qlY3UubormgHiYpx87lk41M1XT3d/0iyNlHs+kcuj6jECKwCuv6CKuTANxFe9MXQod+zEp5BHjxbAa2G6aqFpozwLgub5W7AwOUNcadshQ5zcwdFZOoCJHivk31EiL55jGXY1SiYOYpXEIrqw8/21fIEEVt8jlmXY8N9b9PjHVuotLS+vpElRPWL3dncfZXp4KfuHzDCQXqXWugKMsHhziHnvlZvUg5bH4mjcwLKYGebste0i82TtvZdgaVMml0opW7VaVfBFDx2PesxlwnSRQXBRGkKF/Ab94c9NU3KFQIBG48mFjyBixXQgf+6aqqTEBuujxnjhhn7xOtC1+UIO1XdwmQ85NxeWV80oUyrJw7gcru4/Zf1EYTus4YlMDjo79EpqPuZVugPjIbPlgopZ+lWByqsCeUMinDTOCGrzoByCh6RtfEvYDZ+hz6L6f2Ua8YHVR2jsbTAWYOx37NEOR0ikLErX96h7Nmm4cZ+19IYyBEpBv7R4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: secret-tiger-docker
      namespace: default
    type: kubernetes.io/dockerconfigjson

